version: "3.8"

services:
  frontend:
    build: ./MyEvent-Web-Site
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend-Event
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://root:securepass@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-1


